### PR TITLE
Use Vanilla Boats, Some Cleanup, Optimize Textures, More Cleanup, Port Some Non-Updated Methods

### PR DESCRIPTION
**Pull request by AViewFromTheTop**
Bruh

### CODE REVIEW

**Comment by ghost** [comment]
looks kinda

**Comment by ghost** [comment]
goofy

**Comment by AViewFromTheTop** [comment]
> goofy

???

**Comment by xXNickznXx** [comment]
maybe dont change the code formatting so it doesnt look like you changed everything

**Comment by AViewFromTheTop** [comment]
> maybe dont change the code formatting so it doesnt look like you changed everything

I already told him what I actually changed bruh

**Pull request merged**
